// auto generated by print_keys.py
use num_bigint_dig::BigUint;
use hex_literal::hex;
use makiko::elliptic_curve;

pub fn alice_ed25519() -> makiko::Privkey {
    let private_bytes = hex!("e264980178ad0b28ef8b9a7cad8278f4f9001c52e1f2fc61165d7baa36b53175");
    let public_bytes = hex!("09255d6093be46c9db2f486fd0a946f21f5729127603811e20c2fddbf58592b3");
    makiko::Privkey::Ed25519(ed25519_dalek::Keypair {
        secret: ed25519_dalek::SecretKey::from_bytes(&private_bytes).unwrap(),
        public: ed25519_dalek::PublicKey::from_bytes(&public_bytes).unwrap(),
    }.into())
}
pub static ALICE_ED25519_KEYPAIR_PEM: &'static str = concat!(
    "-----BEGIN OPENSSH PRIVATE KEY-----\n",
    "b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW\n",
    "QyNTUxOQAAACAJJV1gk75GydsvSG/QqUbyH1cpEnYDgR4gwv3b9YWSswAAAIhmfkbhZn5G\n",
    "4QAAAAtzc2gtZWQyNTUxOQAAACAJJV1gk75GydsvSG/QqUbyH1cpEnYDgR4gwv3b9YWSsw\n",
    "AAAEDiZJgBeK0LKO+Lmnytgnj0+QAcUuHy/GEWXXuqNrUxdQklXWCTvkbJ2y9Ib9CpRvIf\n",
    "VykSdgOBHiDC/dv1hZKzAAAABWFsaWNl\n",
    "-----END OPENSSH PRIVATE KEY-----\n",
);

pub fn edward_ed25519() -> makiko::Privkey {
    let private_bytes = hex!("3972dfb17dcf6a949e08d8979ef0722b021379e72c66b549af2a98d3eeae905c");
    let public_bytes = hex!("f2549b117e1f8d9a440a8360e1eab3d5a1d890de70be755a0632832d61c6cc25");
    makiko::Privkey::Ed25519(ed25519_dalek::Keypair {
        secret: ed25519_dalek::SecretKey::from_bytes(&private_bytes).unwrap(),
        public: ed25519_dalek::PublicKey::from_bytes(&public_bytes).unwrap(),
    }.into())
}
pub static EDWARD_ED25519_KEYPAIR_PEM: &'static str = concat!(
    "-----BEGIN OPENSSH PRIVATE KEY-----\n",
    "b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW\n",
    "QyNTUxOQAAACDyVJsRfh+NmkQKg2Dh6rPVodiQ3nC+dVoGMoMtYcbMJQAAAJBPdwHAT3cB\n",
    "wAAAAAtzc2gtZWQyNTUxOQAAACDyVJsRfh+NmkQKg2Dh6rPVodiQ3nC+dVoGMoMtYcbMJQ\n",
    "AAAEA5ct+xfc9qlJ4I2Jee8HIrAhN55yxmtUmvKpjT7q6QXPJUmxF+H42aRAqDYOHqs9Wh\n",
    "2JDecL51WgYygy1hxswlAAAABmVkd2FyZAECAwQFBgc=\n",
    "-----END OPENSSH PRIVATE KEY-----\n",
);

pub fn ruth_rsa_1024() -> makiko::Privkey {
    let n = BigUint::from_bytes_be(&hex!(
        "e72e0e6569dd40cafc4c608c4ee3b7f13956b7e5b301cc8dc47c9e26019b053d"
        "0f9de0ed4856f89c5cf2355f08c41486d7c6840a670e2eaa425a7db58a8e99b3"
        "e46bf2902a1b699de966df734f7b127129909b2e009a102e553f0b683870b127"
        "16569b6e8ab707d5bf52d1575c8093b506f3bf54c2a23d644023ce6d0fbd8a11"
    ));
    let e = BigUint::from_bytes_be(&hex!("010001"));
    let d = BigUint::from_bytes_be(&hex!(
        "ccd54e04256cd90001d45aa7772ee5c86299a78f6ab06962237a9755ed8e4171"
        "fce852676bf5438aa80023b1f4be67c1a2664e903907a3e94fa98640d867c95e"
        "9fc837873c58c1adcfe9ba2624089b45d841bb838be73470f319ccf5541d27dd"
        "e7734a59a242f796d8c6e21129c95ea5b5b7a9ea6346afc55b7f725b4afd18c1"
    ));
    let p = BigUint::from_bytes_be(&hex!(
        "fd9484530f9492f263198e923707318d1b2517546ce6c3eb357e8985551fd95a"
        "6096a1ad74e9ab1715e10cc41c6b075f98f3c8482c4b52c2ea8222faa211cdbd"
    ));
    let q = BigUint::from_bytes_be(&hex!(
        "e962d1151bf00073d3ee5cda8b22a3b03685cf203daf4f9cb110d50dedd52799"
        "92ab6c68dfed18a1e17aadaaf3a524dbc90a6c8569e0d28f16053551acda80e5"
    ));
    let privkey = rsa::RsaPrivateKey::from_components(n, e, d, vec![p, q]);
    makiko::Privkey::Rsa(privkey.into())
}
pub static RUTH_RSA_1024_KEYPAIR_PEM: &'static str = concat!(
    "-----BEGIN OPENSSH PRIVATE KEY-----\n",
    "b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAlwAAAAdzc2gtcn\n",
    "NhAAAAAwEAAQAAAIEA5y4OZWndQMr8TGCMTuO38TlWt+WzAcyNxHyeJgGbBT0PneDtSFb4\n",
    "nFzyNV8IxBSG18aECmcOLqpCWn21io6Zs+Rr8pAqG2md6Wbfc097EnEpkJsuAJoQLlU/C2\n",
    "g4cLEnFlabboq3B9W/UtFXXICTtQbzv1TCoj1kQCPObQ+9ihEAAAIAcCOChXAjgoUAAAAH\n",
    "c3NoLXJzYQAAAIEA5y4OZWndQMr8TGCMTuO38TlWt+WzAcyNxHyeJgGbBT0PneDtSFb4nF\n",
    "zyNV8IxBSG18aECmcOLqpCWn21io6Zs+Rr8pAqG2md6Wbfc097EnEpkJsuAJoQLlU/C2g4\n",
    "cLEnFlabboq3B9W/UtFXXICTtQbzv1TCoj1kQCPObQ+9ihEAAAADAQABAAAAgQDM1U4EJW\n",
    "zZAAHUWqd3LuXIYpmnj2qwaWIjepdV7Y5BcfzoUmdr9UOKqAAjsfS+Z8GiZk6QOQej6U+p\n",
    "hkDYZ8len8g3hzxYwa3P6bomJAibRdhBu4OL5zRw8xnM9VQdJ93nc0pZokL3ltjG4hEpyV\n",
    "6ltbep6mNGr8Vbf3JbSv0YwQAAAEEAl2cdVGalH2a/PWoBJmCDYcNpNKJZoZldp0p52Bqw\n",
    "pCxjzOdQqWzv8xLKm/5bCh03j1mn8BwmKPtzit3Z040W6gAAAEEA/ZSEUw+UkvJjGY6SNw\n",
    "cxjRslF1Rs5sPrNX6JhVUf2VpglqGtdOmrFxXhDMQcawdfmPPISCxLUsLqgiL6ohHNvQAA\n",
    "AEEA6WLRFRvwAHPT7lzaiyKjsDaFzyA9r0+csRDVDe3VJ5mSq2xo3+0YoeF6rarzpSTbyQ\n",
    "pshWng0o8WBTVRrNqA5QAAAARydXRoAQIDBAU=\n",
    "-----END OPENSSH PRIVATE KEY-----\n",
);

pub fn ruth_rsa_2048() -> makiko::Privkey {
    let n = BigUint::from_bytes_be(&hex!(
        "e248796bbb1912c2131adb59e32415bde6f1ed68ca3ba582eb70b9c45e728ab4"
        "9f58d01585a9269a556a0437b494f6fd57713a02437f80b395a92748e272f4ea"
        "95ee818f683d25461d1eae9d024e7f6e19b404c02b13618ee6fd7fd467e7ba62"
        "250f48306c1e726df5e5c83beb80a0e260a0530dfabb8e470b7bbd03fd6804b3"
        "a043c588242ef45659f0223047c929d0fa183aab20052aaba0aa78f468c1b668"
        "4e5742ffc9f65443e2ed068774cf55ef7799f50d32fa920e64834d2b61ab0d8c"
        "9a6561b69b17a28cea51de0f8f9bc7f5d012fe74e2ceb3ebf692a08fd2e23c76"
        "9b9e9d121cda1f26f2a2781741aba1da0353f3dcc2f694f712d654951d609e01"
    ));
    let e = BigUint::from_bytes_be(&hex!("010001"));
    let d = BigUint::from_bytes_be(&hex!(
        "41e470d71a2876f9e4ae51699f67069dc1fe78efa6d42fa22c052b532f5d935e"
        "7d78533fb1284c816c95ee9c7a0d56cef70395accb12f9db519d6c3f2111f097"
        "cf0920d92db580812641a4ff3b88b83acb694c68d9224faa594140540dddc0bc"
        "8ba6239356289791c5a51fe5b2f245e725d409db6c43e96e6ebd9d90e7ddbe60"
        "3402a07c12800e1674f77bbe85bb61be16b3c7606e9aeea35887c2b95b95911f"
        "5a54682f71a7cd4081ade177b69851a9bcd9e3f2ce93ca63dfefe49b9418efa7"
        "d2c33862792e50bfc26923fb975ced69c827e047fa4099e9935c9e5fc3aac2f1"
        "d1663e037ff3a8ac7755031e909b1f0b2ff1ba30f8d34572871444c66b0e1531"
    ));
    let p = BigUint::from_bytes_be(&hex!(
        "f0f31c437f765fc87fcf479a530da6637259e80bda84df779da810a2eb3e26a4"
        "57b2f234e473a3ca74f6696d9c66fafff4eb8cef0e1ac05225c00b1857dc347d"
        "3b20248383d993807a2ec3c5cd32ccdc4bac121c54d12bc92529bf86d1483898"
        "43da68ae7581cee6fe7360e1b7471c98a87c13b0f8662042b62d178d54eb3a87"
    ));
    let q = BigUint::from_bytes_be(&hex!(
        "f06ad6e4fc578f4310f0b6a977af571646f42ac0757ac017a3599c679eb04d6e"
        "b5813e561cf2e6e100bcff381b7aa622c5f9089917dab5765a13d82959b27764"
        "a7b88f7ccb93223aeaadc6771bd9a6b6b67138383805f42c4c5cff58b6c4e7f5"
        "76f0cd4a3193f8e4ca2678fa931dc03f621323799b9c565d2953b5d4c1cc5d37"
    ));
    let privkey = rsa::RsaPrivateKey::from_components(n, e, d, vec![p, q]);
    makiko::Privkey::Rsa(privkey.into())
}
pub static RUTH_RSA_2048_KEYPAIR_PEM: &'static str = concat!(
    "-----BEGIN OPENSSH PRIVATE KEY-----\n",
    "b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdzc2gtcn\n",
    "NhAAAAAwEAAQAAAQEA4kh5a7sZEsITGttZ4yQVvebx7WjKO6WC63C5xF5yirSfWNAVhakm\n",
    "mlVqBDe0lPb9V3E6AkN/gLOVqSdI4nL06pXugY9oPSVGHR6unQJOf24ZtATAKxNhjub9f9\n",
    "Rn57piJQ9IMGwecm315cg764Cg4mCgUw36u45HC3u9A/1oBLOgQ8WIJC70VlnwIjBHySnQ\n",
    "+hg6qyAFKqugqnj0aMG2aE5XQv/J9lRD4u0Gh3TPVe93mfUNMvqSDmSDTSthqw2MmmVhtp\n",
    "sXoozqUd4Pj5vH9dAS/nTizrPr9pKgj9LiPHabnp0SHNofJvKieBdBq6HaA1Pz3ML2lPcS\n",
    "1lSVHWCeAQAAA8DnIIlg5yCJYAAAAAdzc2gtcnNhAAABAQDiSHlruxkSwhMa21njJBW95v\n",
    "HtaMo7pYLrcLnEXnKKtJ9Y0BWFqSaaVWoEN7SU9v1XcToCQ3+As5WpJ0jicvTqle6Bj2g9\n",
    "JUYdHq6dAk5/bhm0BMArE2GO5v1/1GfnumIlD0gwbB5ybfXlyDvrgKDiYKBTDfq7jkcLe7\n",
    "0D/WgEs6BDxYgkLvRWWfAiMEfJKdD6GDqrIAUqq6CqePRowbZoTldC/8n2VEPi7QaHdM9V\n",
    "73eZ9Q0y+pIOZINNK2GrDYyaZWG2mxeijOpR3g+Pm8f10BL+dOLOs+v2kqCP0uI8dpuenR\n",
    "Ic2h8m8qJ4F0GrodoDU/PcwvaU9xLWVJUdYJ4BAAAAAwEAAQAAAQBB5HDXGih2+eSuUWmf\n",
    "Zwadwf5476bUL6IsBStTL12TXn14Uz+xKEyBbJXunHoNVs73A5WsyxL521GdbD8hEfCXzw\n",
    "kg2S21gIEmQaT/O4i4OstpTGjZIk+qWUFAVA3dwLyLpiOTViiXkcWlH+Wy8kXnJdQJ22xD\n",
    "6W5uvZ2Q592+YDQCoHwSgA4WdPd7voW7Yb4Ws8dgbpruo1iHwrlblZEfWlRoL3GnzUCBre\n",
    "F3tphRqbzZ4/LOk8pj3+/km5QY76fSwzhieS5Qv8JpI/uXXO1pyCfgR/pAmemTXJ5fw6rC\n",
    "8dFmPgN/86isd1UDHpCbHwsv8bow+NNFcocURMZrDhUxAAAAgQDsdm+WvIU4fGya53YMBE\n",
    "FFwP4474j1cu83T5z1uXfFdShWLJu0ZZvPRC8zaooLrNAZUX+0AkkqZzxwopbOip/pQVpk\n",
    "tMp2cDu6bxL4u0+oegTe+9mJGga+daKK01Q37gFbY5OyPCL/MkKrhcigh13DYtgjiBTOnq\n",
    "S/UbaT9cfDVAAAAIEA8PMcQ392X8h/z0eaUw2mY3JZ6AvahN93nagQous+JqRXsvI05HOj\n",
    "ynT2aW2cZvr/9OuM7w4awFIlwAsYV9w0fTsgJIOD2ZOAei7Dxc0yzNxLrBIcVNErySUpv4\n",
    "bRSDiYQ9pornWBzub+c2Dht0ccmKh8E7D4ZiBCti0XjVTrOocAAACBAPBq1uT8V49DEPC2\n",
    "qXevVxZG9CrAdXrAF6NZnGeesE1utYE+Vhzy5uEAvP84G3qmIsX5CJkX2rV2WhPYKVmyd2\n",
    "SnuI98y5MiOuqtxncb2aa2tnE4ODgF9CxMXP9YtsTn9XbwzUoxk/jkyiZ4+pMdwD9iEyN5\n",
    "m5xWXSlTtdTBzF03AAAABHJ1dGgBAgMEBQY=\n",
    "-----END OPENSSH PRIVATE KEY-----\n",
);

pub fn ruth_rsa_4096() -> makiko::Privkey {
    let n = BigUint::from_bytes_be(&hex!(
        "ed89a6dda8e80c2d90d6ef0b69fa1ff02045ba736c015f88a8a6e9bd7b13dc41"
        "40c421a754d30a7fa1efe15686547d69e8efe42d076e7262b7df4e9e814b80ec"
        "e236744b00bf95c748324e001a55e140ee7c58d4d0e02ad58c08b9df060a775f"
        "c85b8ef60fd0db8275a1402cc39107f06fb883e7115a838dedfba78a46773a74"
        "46f6c8b3a2c515dbeec31351b0617545201211fd033a03b126ebe345d8628b06"
        "5390cbea2775bdee8cff35e5ed6ecb7f9f2b7e1527c733b32cb91043c2fd361a"
        "d745af5ed7bd431f7e98edb436b35cabc755176cb5e72886c6040c09ee744d43"
        "99a63bd8facafb5c2a2cc9c523e582070859a8c8ae79c0da9195cd059737cdc5"
        "d760b1c4bb77ffb5cc08f34d7a5238980945b1796f12aee31197fe85b4fa22b4"
        "402ee76d1cf0971022c3630acbe5d28f38a03f5fce2e54e1e2a5f20e119b785e"
        "4a1060302a685abe0d2760c9a4b3ddaf90b8e03cc7a28881e8e6f5ce27b1a175"
        "b3d215ba10e76c3bf61052ac9ae79cbf2fee89e266679f9e981a850361983395"
        "6ce39238fbd64e98ce717b88861f954ff1ef9641a3cbf071fa9607277ba21656"
        "bdc662eef52f8119542f35919968c3a8a61fdea485589758945bb165249aa500"
        "ca5f1d10ad96a82d4f308286e36efd5768cc6ab00469ff0f89dd9fd8fedfc027"
        "6934d8a1383f0769cf7dacf8c5aa9e3bca0e923f53c849ec9c974c41d2033f09"
    ));
    let e = BigUint::from_bytes_be(&hex!("010001"));
    let d = BigUint::from_bytes_be(&hex!(
        "2feb560b5f78b88434b4f7726105c18daaa506712477be730e3ae5ea80bac7f3"
        "2e02a31b63a45378de0d4b732e143b5cb34e39c4cfbbfb3d69049692a958b700"
        "92be1385d1f7d45a6879257d25d2ef672ef54ce259e4ef1f3769c73d73b586d1"
        "7ed4e1a948158542f341fd754a5aa6b45d8566aea5b491d77f0c068781a1a9dc"
        "2d38b9d26b62c0ff26529a421f87f9a5614be3ef1bc887582496efb97666a2cf"
        "3aea7a0899bf49faa6dd115d7a21a0d1f5254c012e8e2422e041d1432a41f4b9"
        "43765e638eb832a356e1b90a63029a0e595f1423ad2a9de55a6b1496a8513409"
        "102515ebb6e45e0300cb1a4537f1a3e2914fad1a17009ee438fc7468cd51c7a3"
        "df476887f187ca1e9469fb0793a1afbbb2c60f64a1fe19776f3d96486d2e15d6"
        "208b037e519e91423deaa87954d59aba3bfa316a93c3ffba16b57d8e03daa509"
        "7b0aee81ec099f028ef0c814908a871666e25d004bb276ea3c4f608f20194175"
        "1ff56a9e12fc40ad1b9cbc792fb535e38b5d384163b4fab42c20766290cbc4f4"
        "32db6d094de3cb9494e3d42a5465640360252e5b83b406952463ae0ba4ff1734"
        "d2d56ee2a2117a743a66f5598f54555aa464f08774e7d0ec72ceef95c50f4554"
        "5108b1409a2dab28062dbcdb35f067fb9431ec33a946b8c7e20c7d477d778ffd"
        "680fb2a4b0dbf04cca3da016f5726a955645387d25faffdba9a2c7a2f1460381"
    ));
    let p = BigUint::from_bytes_be(&hex!(
        "f9cbda75eea8ca71a5bd0a586d9793077779fbb11ebc1c6e31183dfa79d93f88"
        "ac3406d115cd395b3679dc32ad136c94a8d6a54383928b92391c33b3cfc76c45"
        "f23431e7b9e5735e97458b9c083c7fb83353aae008d5a8cb92ded469081ebcb5"
        "43885f7dceb0f3375cf4f6b64b6251304bc6d8fcc25e29b20affb7a9feeb04cf"
        "6b481ed05bfe68e5ac7c2054ce4fe83de5c48bd44d383ae35ad1f8a5376ac194"
        "c83017113d5163e8439920c2afc972dded06d0e63a2e2e0d484fc48d10e81a04"
        "0ca44a9e9805df1ef4dfa740cbde7d20ef7c08ea392455410328a653aff1e2bb"
        "9d8800ff39578a5a5229cf97b24db66379e356744e96aa3ddf0a256df5cdd5d1"
    ));
    let q = BigUint::from_bytes_be(&hex!(
        "f36fdc739bb0b7c933e5e086023aab31235f59cb4ec16da80054e430ee849b71"
        "efb34f7ee74eaf091c4a5519bc706401c048acb41d3fb9786ebd88eb7dfa0f26"
        "ec0eba2f37d823af8235bb97bf7423fe918683e7e0121fbb8a56ce2e908ce156"
        "208057ed6b6e39ca542d588e44dcffa3db4a9245a9ccceae83d63a354a005a2a"
        "b7b49612ecb1967f49d6aa2477e6211e482edd69e8e4cbe6206aff487c6eb4aa"
        "38270f8289c308c4eca9fdcb78df73d1fd34c3893fe41b69152ef20a0081fdf4"
        "45bc7b533ff23bc9e0d60e0b80cf7d995ba3d4504a0df457d55f446106d6d553"
        "f07198cab9dccc0753c42a1f94418b81c83a97db8c1d01516b804f02ef07cbb9"
    ));
    let privkey = rsa::RsaPrivateKey::from_components(n, e, d, vec![p, q]);
    makiko::Privkey::Rsa(privkey.into())
}
pub static RUTH_RSA_4096_KEYPAIR_PEM: &'static str = concat!(
    "-----BEGIN OPENSSH PRIVATE KEY-----\n",
    "b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn\n",
    "NhAAAAAwEAAQAAAgEA7Ymm3ajoDC2Q1u8Lafof8CBFunNsAV+IqKbpvXsT3EFAxCGnVNMK\n",
    "f6Hv4VaGVH1p6O/kLQducmK3306egUuA7OI2dEsAv5XHSDJOABpV4UDufFjU0OAq1YwIud\n",
    "8GCndfyFuO9g/Q24J1oUAsw5EH8G+4g+cRWoON7funikZ3OnRG9sizosUV2+7DE1GwYXVF\n",
    "IBIR/QM6A7Em6+NF2GKLBlOQy+ondb3ujP815e1uy3+fK34VJ8czsyy5EEPC/TYa10WvXt\n",
    "e9Qx9+mO20NrNcq8dVF2y15yiGxgQMCe50TUOZpjvY+sr7XCosycUj5YIHCFmoyK55wNqR\n",
    "lc0FlzfNxddgscS7d/+1zAjzTXpSOJgJRbF5bxKu4xGX/oW0+iK0QC7nbRzwlxAiw2MKy+\n",
    "XSjzigP1/OLlTh4qXyDhGbeF5KEGAwKmhavg0nYMmks92vkLjgPMeiiIHo5vXOJ7GhdbPS\n",
    "FboQ52w79hBSrJrnnL8v7oniZmefnpgahQNhmDOVbOOSOPvWTpjOcXuIhh+VT/HvlkGjy/\n",
    "Bx+pYHJ3uiFla9xmLu9S+BGVQvNZGZaMOoph/epIVYl1iUW7FlJJqlAMpfHRCtlqgtTzCC\n",
    "huNu/VdozGqwBGn/D4ndn9j+38AnaTTYoTg/B2nPfaz4xaqeO8oOkj9TyEnsnJdMQdIDPw\n",
    "kAAAdALFR+yCxUfsgAAAAHc3NoLXJzYQAAAgEA7Ymm3ajoDC2Q1u8Lafof8CBFunNsAV+I\n",
    "qKbpvXsT3EFAxCGnVNMKf6Hv4VaGVH1p6O/kLQducmK3306egUuA7OI2dEsAv5XHSDJOAB\n",
    "pV4UDufFjU0OAq1YwIud8GCndfyFuO9g/Q24J1oUAsw5EH8G+4g+cRWoON7funikZ3OnRG\n",
    "9sizosUV2+7DE1GwYXVFIBIR/QM6A7Em6+NF2GKLBlOQy+ondb3ujP815e1uy3+fK34VJ8\n",
    "czsyy5EEPC/TYa10WvXte9Qx9+mO20NrNcq8dVF2y15yiGxgQMCe50TUOZpjvY+sr7XCos\n",
    "ycUj5YIHCFmoyK55wNqRlc0FlzfNxddgscS7d/+1zAjzTXpSOJgJRbF5bxKu4xGX/oW0+i\n",
    "K0QC7nbRzwlxAiw2MKy+XSjzigP1/OLlTh4qXyDhGbeF5KEGAwKmhavg0nYMmks92vkLjg\n",
    "PMeiiIHo5vXOJ7GhdbPSFboQ52w79hBSrJrnnL8v7oniZmefnpgahQNhmDOVbOOSOPvWTp\n",
    "jOcXuIhh+VT/HvlkGjy/Bx+pYHJ3uiFla9xmLu9S+BGVQvNZGZaMOoph/epIVYl1iUW7Fl\n",
    "JJqlAMpfHRCtlqgtTzCChuNu/VdozGqwBGn/D4ndn9j+38AnaTTYoTg/B2nPfaz4xaqeO8\n",
    "oOkj9TyEnsnJdMQdIDPwkAAAADAQABAAACAC/rVgtfeLiENLT3cmEFwY2qpQZxJHe+cw46\n",
    "5eqAusfzLgKjG2OkU3jeDUtzLhQ7XLNOOcTPu/s9aQSWkqlYtwCSvhOF0ffUWmh5JX0l0u\n",
    "9nLvVM4lnk7x83acc9c7WG0X7U4alIFYVC80H9dUpaprRdhWaupbSR138MBoeBoancLTi5\n",
    "0mtiwP8mUppCH4f5pWFL4+8byIdYJJbvuXZmos866noImb9J+qbdEV16IaDR9SVMAS6OJC\n",
    "LgQdFDKkH0uUN2XmOOuDKjVuG5CmMCmg5ZXxQjrSqd5VprFJaoUTQJECUV67bkXgMAyxpF\n",
    "N/Gj4pFPrRoXAJ7kOPx0aM1Rx6PfR2iH8YfKHpRp+weToa+7ssYPZKH+GXdvPZZIbS4V1i\n",
    "CLA35RnpFCPeqoeVTVmro7+jFqk8P/uha1fY4D2qUJewrugewJnwKO8MgUkIqHFmbiXQBL\n",
    "snbqPE9gjyAZQXUf9WqeEvxArRucvHkvtTXji104QWO0+rQsIHZikMvE9DLbbQlN48uUlO\n",
    "PUKlRlZANgJS5bg7QGlSRjrguk/xc00tVu4qIRenQ6ZvVZj1RVWqRk8Id059Dscs7vlcUP\n",
    "RVRRCLFAmi2rKAYtvNs18Gf7lDHsM6lGuMfiDH1HfXeP/WgPsqSw2/BMyj2gFvVyapVWRT\n",
    "h9Jfr/26mix6LxRgOBAAABAEPGsW7sUi6JPQ9YsomTzsEMUazh45EyNj02iP1EQgC8Q4AY\n",
    "z/qm5u9pDQ+YRxGLxe3u01/aEJmXV+RbQ4Tb73uhGARtZ/V9qlmNyoZrucjbXuyQ71Seah\n",
    "IxtcoR4/Zj+ce7CvDKrw1Hk3uZlp5C7PmD9X2uqofTZ691AMYiAoPgdtfsB1ZQSo3MQ9YT\n",
    "VRZeVWwfHTlE+CtkDohph3QcAlkGiBaGKC8ynCEF92cCxgv+Tx1chwJlA7aT8GmGcvrpdD\n",
    "J/cWceBc+e/MA3otBlA6EhdZOoF18yNrrC3wp0vyy3/EupF+3pQX1NyUZbHx0ehJOjGvPG\n",
    "72TzZWga3tWVb1AAAAEBAPnL2nXuqMpxpb0KWG2Xkwd3efuxHrwcbjEYPfp52T+IrDQG0R\n",
    "XNOVs2edwyrRNslKjWpUODkouSORwzs8/HbEXyNDHnueVzXpdFi5wIPH+4M1Oq4AjVqMuS\n",
    "3tRpCB68tUOIX33OsPM3XPT2tktiUTBLxtj8wl4psgr/t6n+6wTPa0ge0Fv+aOWsfCBUzk\n",
    "/oPeXEi9RNODrjWtH4pTdqwZTIMBcRPVFj6EOZIMKvyXLd7QbQ5jouLg1IT8SNEOgaBAyk\n",
    "Sp6YBd8e9N+nQMvefSDvfAjqOSRVQQMoplOv8eK7nYgA/zlXilpSKc+Xsk22Y3njVnROlq\n",
    "o93wolbfXN1dEAAAEBAPNv3HObsLfJM+XghgI6qzEjX1nLTsFtqABU5DDuhJtx77NPfudO\n",
    "rwkcSlUZvHBkAcBIrLQdP7l4br2I6336DybsDrovN9gjr4I1u5e/dCP+kYaD5+ASH7uKVs\n",
    "4ukIzhViCAV+1rbjnKVC1YjkTc/6PbSpJFqczOroPWOjVKAFoqt7SWEuyxln9J1qokd+Yh\n",
    "Hkgu3Wno5MvmIGr/SHxutKo4Jw+CicMIxOyp/ct433PR/TTDiT/kG2kVLvIKAIH99EW8e1\n",
    "M/8jvJ4NYOC4DPfZlbo9RQSg30V9VfRGEG1tVT8HGYyrnczAdTxCoflEGLgcg6l9uMHQFR\n",
    "a4BPAu8Hy7kAAAAEcnV0aAECAwQFBgc=\n",
    "-----END OPENSSH PRIVATE KEY-----\n",
);

pub fn eda_ecdsa_p256() -> makiko::Privkey {
    let private_key = elliptic_curve::SecretKey::<p256::NistP256>::from_be_bytes(&hex!(
        "d8fd4505ee0da7db5269de892c3d1a577a1a46188df892478ee7550c359abb1a"
    )).unwrap();
    let privkey = makiko::pubkey::EcdsaPrivkey::<p256::NistP256>::from(private_key);
    makiko::Privkey::EcdsaP256(privkey)
}
pub static EDA_ECDSA_P256_KEYPAIR_PEM: &'static str = concat!(
    "-----BEGIN OPENSSH PRIVATE KEY-----\n",
    "b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAaAAAABNlY2RzYS\n",
    "1zaGEyLW5pc3RwMjU2AAAACG5pc3RwMjU2AAAAQQQ8fwweAGpAvTJ3Dd/UOArK2A4FWyx5\n",
    "kzV0rMDMDglGxhhvU+jIHcpHitu2eeZPRi9SJrcTfVMHStig6pgRKqVAAAAAoKTD2uukw9\n",
    "rrAAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDx/DB4AakC9MncN\n",
    "39Q4CsrYDgVbLHmTNXSswMwOCUbGGG9T6MgdykeK27Z55k9GL1ImtxN9UwdK2KDqmBEqpU\n",
    "AAAAAhANj9RQXuDafbUmneiSw9Gld6GkYYjfiSR47nVQw1mrsaAAAAA2VkYQECAwQ=\n",
    "-----END OPENSSH PRIVATE KEY-----\n",
);

pub fn eda_ecdsa_p384() -> makiko::Privkey {
    let private_key = elliptic_curve::SecretKey::<p384::NistP384>::from_be_bytes(&hex!(
        "48881a10e3140e41e6c4da6c7dfe4cfa3db82d10526f5707dee2722e29e5545d6840d14e54efd37e6eae9c20490729c1"
    )).unwrap();
    let privkey = makiko::pubkey::EcdsaPrivkey::<p384::NistP384>::from(private_key);
    makiko::Privkey::EcdsaP384(privkey)
}
pub static EDA_ECDSA_P384_KEYPAIR_PEM: &'static str = concat!(
    "-----BEGIN OPENSSH PRIVATE KEY-----\n",
    "b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAiAAAABNlY2RzYS\n",
    "1zaGEyLW5pc3RwMzg0AAAACG5pc3RwMzg0AAAAYQTHZW4k5tFzU/ewoWw2tR8LWiS5l9mz\n",
    "DDl0gVEGxBGcwLmEvrtGwTYLARPHkAOy0UNY5ezjM9FKi3dvSEBuCflq50mst7cc07HaqH\n",
    "kGoQhSZ94yhBRjVnGHGYJNk0gY/AEAAADQEZtu4hGbbuIAAAATZWNkc2Etc2hhMi1uaXN0\n",
    "cDM4NAAAAAhuaXN0cDM4NAAAAGEEx2VuJObRc1P3sKFsNrUfC1okuZfZsww5dIFRBsQRnM\n",
    "C5hL67RsE2CwETx5ADstFDWOXs4zPRSot3b0hAbgn5audJrLe3HNOx2qh5BqEIUmfeMoQU\n",
    "Y1ZxhxmCTZNIGPwBAAAAMEiIGhDjFA5B5sTabH3+TPo9uC0QUm9XB97ici4p5VRdaEDRTl\n",
    "Tv035urpwgSQcpwQAAAANlZGEBAgMEBQ==\n",
    "-----END OPENSSH PRIVATE KEY-----\n",
);

pub fn encrypted_rsa() -> makiko::Privkey {
    let n = BigUint::from_bytes_be(&hex!(
        "dd2621c85ff9ae71346a9bc9ce267f33c5138aae527505557304cc75f84792a4"
        "de7f90ba28c5552dbee4f298633012e6fee03192aa516ef5fd76775bf0a21ecd"
        "511c7acb3d83f59e280130d43881a69be0b4bbac12800da57dcc06bf6b5a4459"
        "5097844c28326a49362de50ce471639dfb3ec7acb229dd1ad1e7707cddb20c51"
        "64417fb1efcdaff9869e09beb48b3aa1dfe2d449e00329ee9cf0392f241fe216"
        "8a79f5dd0b82f41d7b9efe8bed8bfd77463e462c37bb55341985402d5739c7ff"
        "ee3fd9ce409463b3d9e01e9c3fb49e7a2c1cac35aaf32aebba2d76a39576507f"
        "b62706ee4535577ac386e1acdb1cebf0a7e5b4fad9e4ccae3bf8ebe13276306a"
        "4ad6c0805c504b5794be59abbb073f3ebff6d0c891c9951721001166c6b38483"
        "519e9a0f789d51751a577d865604b94f7e382fe7c2b1b83e9e2deb2e70c1a5eb"
        "ee755e5adb5a911d969760dcfc42ae4a4e469ebdf4d85b51f9bc67430568232d"
        "250b588ac4e5f04c294f9472ba7e0960e5d309519ebd4dcde8bb4772f31c3359"
    ));
    let e = BigUint::from_bytes_be(&hex!("010001"));
    let d = BigUint::from_bytes_be(&hex!(
        "a3d30cb1a84f89677942047861cbe8ed4bf0270aee309c2be9d1c3391d1cc048"
        "7c3f19d29e4358cf539bbd0f20634b8d6d805d98ddad07bb18f1ba881461b4d9"
        "ba5d93a59dc3749f9dd90bf81a8809096e53d4b72ad94bc2adc707b4a3ed31b6"
        "cc5a01fa7cc8a42dea01e3ad4249b15725f922e80eefae48a0f8873f28e82df1"
        "d9881ff58bc4deb8c57dab9067a4c0618c3e37af265091ae9ef9e212c6fb0b7c"
        "5146f9d8af1f6a81b0c35ea3ffec756ef74d48a49700a2a4bec7147cc2221ec2"
        "5af45a1b6b171e22acdc21b56150b52e28b647e4722926f6479ccabaf19c454b"
        "85597201fb319b31768542e3ffd29536b87032376e76943227d47529afaa80f7"
        "258fa7bd6921262844b24f23bcbbe1dc5ffa92cd6001570177f5c32fbb7bf010"
        "6559465dacd0a0f96783bfea3456adb99bfbbf5a316a5c737dec2a081bb608b3"
        "e5b05f613752777a88740433afeeba3c4f1ab09397e4697861159afbfd2621c3"
        "5f114b73e58eddad02cd2842b18d4aa5224e922b0e1687e0b4cab7111a30e751"
    ));
    let p = BigUint::from_bytes_be(&hex!(
        "fc583b4364a88e0ff493a00e0928a3c95f9552e827ef0433e1ee97ad44f9517f"
        "ce37f450bd2f4d723f188462767584822cf541ab49f7ad5042b7bc765c2982bd"
        "9a324728ef68b165b6192ae1f822947b83354bbe30dc13c1be5528cf8efa71dd"
        "96a46144efb94fa8679cd2aa819976df9264b0b81241a50d359919de1c63b2c9"
        "cb74eefcde6c0dc219526fd07e73bcf2c7f0eb7bfc94bf8fbb0c3642e48a92a2"
        "a6d810c459dc4ca831cfd467341ba3c5c39000a5255c12781019f0e8bc251f85"
    ));
    let q = BigUint::from_bytes_be(&hex!(
        "e05a37b4301f91250d9b581a18802a425f320df3e57f500654a41f29a1322ed5"
        "1339bf54bb1db7e26d2f0de8bd0170d23b5a3133184803f2e2395ee2635355bc"
        "fb1a97e8abe8ba6f5a44aa8d0f15cc45774d762bbf50fdc470d46968754eede4"
        "84f500c80772669ea00bc90c08ce9d0d75a68ae32f23ed8e1069b4a496ab52eb"
        "0d7b275b0abe503ef7c8fc35445b49e43e7ebf434bcdf87c694b5ae2e22c8345"
        "7b04652a77e90cfaf6c130251f05cbda5a3474ecf3896ef90997e25ef2bccac5"
    ));
    let privkey = rsa::RsaPrivateKey::from_components(n, e, d, vec![p, q]);
    makiko::Privkey::Rsa(privkey.into())
}
pub static ENCRYPTED_RSA_KEYPAIR_PEM: &'static str = concat!(
    "-----BEGIN OPENSSH PRIVATE KEY-----\n",
    "b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABD/ZI+VXu\n",
    "eliz+nw049g3JxAAAAEAAAAAEAAAGXAAAAB3NzaC1yc2EAAAADAQABAAABgQDdJiHIX/mu\n",
    "cTRqm8nOJn8zxROKrlJ1BVVzBMx1+EeSpN5/kLooxVUtvuTymGMwEub+4DGSqlFu9f12d1\n",
    "vwoh7NURx6yz2D9Z4oATDUOIGmm+C0u6wSgA2lfcwGv2taRFlQl4RMKDJqSTYt5QzkcWOd\n",
    "+z7HrLIp3RrR53B83bIMUWRBf7Hvza/5hp4JvrSLOqHf4tRJ4AMp7pzwOS8kH+IWinn13Q\n",
    "uC9B17nv6L7Yv9d0Y+Riw3u1U0GYVALVc5x//uP9nOQJRjs9ngHpw/tJ56LBysNarzKuu6\n",
    "LXajlXZQf7YnBu5FNVd6w4bhrNsc6/Cn5bT62eTMrjv46+EydjBqStbAgFxQS1eUvlmruw\n",
    "c/Pr/20MiRyZUXIQARZsazhINRnpoPeJ1RdRpXfYZWBLlPfjgv58KxuD6eLesucMGl6+51\n",
    "XlrbWpEdlpdg3PxCrkpORp699NhbUfm8Z0MFaCMtJQtYisTl8EwpT5Ryun4JYOXTCVGevU\n",
    "3N6LtHcvMcM1kAAAWQpD1bUsjAh7P76SomusWv7Kja9b6iYW6mA13WVWEw5H1RmYd90rKN\n",
    "A5MkeQe+muU3Ow61nZv5HX1e4Gveh1nUSWfYWvlWL6rtrt9EepXrwyKNt9aBOKH2VIpHdu\n",
    "uqRrH9woBHuzsmfPCbeRmk0luuIfvAjX1HNHCUL3AYvJCrAGR72dqduMd0LGqxnZeMs9Rz\n",
    "68cYiY6zzE6E2k8W8Vws4ibjEEQ85/z60tFYqXY+4ELyXmVv845MtME3y4e1KOikV/F4+7\n",
    "Fk6KjU3nsbl+a4B7gKx0e45G37cZqb9fIQWgB1oPhaJinrPeCrfvx0RMpIzjmboCO9+JnF\n",
    "FoSrW6fKEQ4Z9KqPzLaUS1MTbd0XPt/lcbCvOiqD2PIIKcIg1dSppMnol4ralJioyLMezr\n",
    "tv6npt5uyfHbg5zAYSKZt+r8l+UnEsporUBfkGQLmY4Vnw/rfWbk6WIeznERpOjqmWrBgj\n",
    "Ll5fTAqVyBZMMv6PDiiJik7DLRYtX7hgnM45zcp3fch8cjj+LArrRPhjBn2BPZB1ljbXoP\n",
    "lOYAJ+VHG4ee36XMZSVXJN4PKsijATEgwuBfqiM24clEciN5EbnBA/eUN3UWwQjkjkBHX8\n",
    "KuuEkuUyj8G4ycDSjcNAHfxD7j7eh46im9K6vJMtqhWktjVUtuIAfag8S8S3kqr6v64QVx\n",
    "+0C/EOHDnxYKjVo3QFJcTwfdD3FZyB2k71hjvhNXEywOr4kf1QO0NwIjHqjpsreAyeXEUT\n",
    "XlbUpxFBJk9gV9AOQJteVFFgRvFqNq04kX4XCHRkc7GmnYYnuq/1WWb6iC4B9LkPYsyZon\n",
    "HliZaYMhT5FH3bB6LR+rL98iiRfvPHaAcLVBpM3LILEU6g/CPaqxt7msGciYpVFNllt+6B\n",
    "glOx0CPn121elU7KyXUSiGNU9zIrpUFPAFnhMOD7s6wKmQ3arIMYLzFp5sPJJRlMQawLJG\n",
    "VHBk8RUWmKNKTr4D6heS1FKEuCpQdOp+gtWHz/bgm+TV+smMBNV+a9+Ys3nH/zmoGp82GV\n",
    "oPwAU1x9W/eUtPxPw8VGgQUzyu68mIjj8vCvdD/omlfsf4gMQZcefW1IhtbQUiH9A3IMqI\n",
    "s2CusN5PDHqywfIVuraLKtL7ZYMYsWSKpJkb6ndwhM0BJnANdTvH7vKsvDRHjfqXNR05E3\n",
    "89W/u8X18Z11eGHvMHfrNWU0izne4PWRP0dY7k1h8D6htRXqMuTtBuGQAXuRpVi2pb24eC\n",
    "4oTEf0jJTcFaYLt8fpfYBFAAUlenr9J8uQ5qKEbynkEPtXM5z/kC5DT1v66c4Vo8yR7Uyz\n",
    "lc1HUr1NHVdaQCZnbq/kUeCMuTCjD/q62+XaRnchxL8whz9Dfp6AdQzWxO0VlywUDYNpiA\n",
    "JIunw1B7ormEBLLkn1p5+KK91R4if1Wh7XGcqKJcZn8gNcY6oIV820yKa0gPB3SsRHxI0E\n",
    "+il/Lmy/TX/6QvLQgYpCKxUPk5FqqPwMLZQg45NnOmRSGMkX2iQ2gg41AKlMXziJvMDA1R\n",
    "gTWW85eiDKqaytHfS4MTg0Vfgdx+Djjek8nzJ2kJFSBWEENT8MRR0+OJp2/tw3VKgW9ZDb\n",
    "I3dMkx/VPMO9pQJpQB6pJJQSA7aMNZl1OVmOpp56XZH0jVqCx4HlOInmY7e+eftMk9AM9n\n",
    "cS5Rfr3vTvpyN2DvDVsfNQ0AWVqqRM4iGygIG3QWnEn7EZaGL3+4rA2tVCPTD1nLmWvgcw\n",
    "JLOH134pBgz0GCed/kOijKvxG+cmZsl8p9W6Yi61FwsidNKvy71MOwlAlHvWr7IOa37WlM\n",
    "doc7ZTn/lNHFf3m2JxBFOzXqy88G/vFxHXfEiZkT0x4XKXKmNLXqFb5lWCRAStRtAWhi2I\n",
    "Ck8ndkJhx+0Og5jQKtdDfk42d9s=\n",
    "-----END OPENSSH PRIVATE KEY-----\n",
);

pub fn encrypted_ed25519() -> makiko::Privkey {
    let private_bytes = hex!("826246ef3ed7700959c7b2710cbd0f38baa760b393e461567e4d8467e6770194");
    let public_bytes = hex!("01a1edfb698c7645b3180380b5306e09aa4222c079b9ec0f02f38a22e836c0a8");
    makiko::Privkey::Ed25519(ed25519_dalek::Keypair {
        secret: ed25519_dalek::SecretKey::from_bytes(&private_bytes).unwrap(),
        public: ed25519_dalek::PublicKey::from_bytes(&public_bytes).unwrap(),
    }.into())
}
pub static ENCRYPTED_ED25519_KEYPAIR_PEM: &'static str = concat!(
    "-----BEGIN OPENSSH PRIVATE KEY-----\n",
    "b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABAnUPbYHd\n",
    "WthhgytMG2mFLLAAAAEAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAIAGh7ftpjHZFsxgD\n",
    "gLUwbgmqQiLAebnsDwLziiLoNsCoAAAAoN+it8qLfEr263uVqcQG4Zg2bR4Ey5yj2bwOyA\n",
    "JPROjjfeiNDncRjY42dnhg1nV/WwPAXFoEvEWIltl1VWz+ypCz4sPqVgKhxYuimnWR4vxW\n",
    "f+shjPGKqNZPEurQqfCNk52YkricHkHH3057KaPRqZIO3FIbmIF5UGFQ8R/JD88H/1MS5y\n",
    "V7mcUEIaoQY2J0bC79O1+rOKihjWL9ViXo0oI=\n",
    "-----END OPENSSH PRIVATE KEY-----\n",
);

pub fn encrypted_ecdsa_p256() -> makiko::Privkey {
    let private_key = elliptic_curve::SecretKey::<p256::NistP256>::from_be_bytes(&hex!(
        "ad18e77b6941aaba4496a348ec21a863b6fbac8d456c508ce1cd90da7d00968d"
    )).unwrap();
    let privkey = makiko::pubkey::EcdsaPrivkey::<p256::NistP256>::from(private_key);
    makiko::Privkey::EcdsaP256(privkey)
}
pub static ENCRYPTED_ECDSA_P256_KEYPAIR_PEM: &'static str = concat!(
    "-----BEGIN OPENSSH PRIVATE KEY-----\n",
    "b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABDoplaOYE\n",
    "SFqk8RQ347BqFBAAAAEAAAAAEAAABoAAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlz\n",
    "dHAyNTYAAABBBO2ZeXdaWAUr4ns8U8/bQag2djDbbcH1oIHq1vopf1kYSZN+8+qVt/vWBd\n",
    "3EppRKT3zIgOe4hvm7se1ILL+IjL8AAACwpwnyyidk/qyzfBrFjkRUVOQV71YehKc2aguH\n",
    "0GPnr05OfK1RZV2DJYkHOXHDA1h7aW/ks11PI5su0+zPaqlLHXCyDgKCwL0UMpSTRVCfIN\n",
    "3Rn34VMwIZRm5pLmhgnieF7AedMtl57r8JC9WwiOvSBog5fyKICyaCmIe8nxH7iABbyvWl\n",
    "R1twhj5we06/k4ZtG2YFQWHa7XZsZ5tK4EBvoDZZ2NapNEKwEgMtE92Diq0=\n",
    "-----END OPENSSH PRIVATE KEY-----\n",
);

pub fn encrypted_ecdsa_p384() -> makiko::Privkey {
    let private_key = elliptic_curve::SecretKey::<p384::NistP384>::from_be_bytes(&hex!(
        "d5e1163bd7efb7b0e2c7554e8dca5cf66eaedd345d54f8734832070997baf782575a660cf57fc71b98deded3a29f22a1"
    )).unwrap();
    let privkey = makiko::pubkey::EcdsaPrivkey::<p384::NistP384>::from(private_key);
    makiko::Privkey::EcdsaP384(privkey)
}
pub static ENCRYPTED_ECDSA_P384_KEYPAIR_PEM: &'static str = concat!(
    "-----BEGIN OPENSSH PRIVATE KEY-----\n",
    "b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABCsgNRLfR\n",
    "jR5HahwAV59KKRAAAAEAAAAAEAAACIAAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlz\n",
    "dHAzODQAAABhBE90bl1WvFWLHVcWVUpU90z+h5Q0aaGGOQibbyxMB3y7tDHE2O8p7EbeEj\n",
    "pzqUAnANUL7iayGMRB5f/442POVjV5wOOJyBKCudpNHFzpXC+r2G2L1X5Z2bqS0imfRKvu\n",
    "JwAAAODp2hnAQw1CYUICaZ79b4wAl/mJ7t4/68rTeMbw1zLm0wFYv6t9XI6Li4mdt1X163\n",
    "X1LMELTZcU98228jbqVretidia5f0naiVSkyN+9NbMu3yhQGYVZAAbSSMaPf17P8yXV+sr\n",
    "EUsp8SxIVna3uHqh70EAAxrfcWxgbL2PN+DXYmhpr0NaNqu8SF9X5+nCMG3uWz72XA09dw\n",
    "n34tqf2DsGklWUtOMuk3NuYe1gzy+gZZ+t2mhKayfPA/3ko/pTK/UJYeYmhBCxlOHDhtKr\n",
    "zBM5+Xu+gB5dlB6srLzNxEXdDw==\n",
    "-----END OPENSSH PRIVATE KEY-----\n",
);

